### ISSUE TITLE
Adding a license

### ISSUE THREAD

**Issue by moore3071** [CWDG/open-source-club-website#186]
The repo needs consent from all contributors to change the license. The proposal is for licensing the website under the MIT license.
- [x] @egladman 
- [x] @oslerw 
- [x] @benlk 
- [x] @bsilvereagle 
- [x] @Nefari0uss 
- [x] @afuhrtrumpet 
- [x] @paradigm 
- [x] @J3RN 
- [x] @moore3071
- [ ] @deadant2
- [ ] @jib5920
- [ ] @ryanconnorh0

**Comment by J3RN** [comment]
I'm in favor. MIT is my go-to.

**Comment by keeakita** [comment]
I'm on board, but we may already implicitly have everyone's consent since `bower.json` says this project is MIT? In any case, we need an explicit LICENSE file.

**Comment by J3RN** [comment]
Technically, the MIT license says:

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

So uh... You may have been in violation of your own license the whole time?

**Comment by moore3071** [comment]
hm, @oslerw, so should we wait for full consent from participants due to that technicality?

**Comment by keeakita** [comment]
@J3RN brings up a really good point. We should make sure we have everyones explicit permission, THEN add a LICENSE file.

**Comment by bsilvereagle** [comment]
MIT works with me, but I think I'm late to the party.

**Comment by moore3071** [comment]
Consent is still appreciated as far as legality goes.

**Comment by keeakita** [comment]
Bueracracy exists for a reason. The license just added to this repo is invalid. Get permission or remove unapproved content. We're the OPEN SOURCE club, there is no excuse for us to get licensing wrong, this is a very well defined situation legally with plenty of precedent that says we need approval from contributors. Please do not close this issue until that happens or offending commits are removed.

**Comment by Nefari0uss** [comment]
I'm voting for the MIT license.

**Comment by egladman** [comment]
It was a hindsight on my part for not including the license during the projects initial creation. It was **always** my intention to license the project under the MIT License. I just forgot. We should **not** make a big deal of this. If I remembered to license this back in September we wouldn't be having this conversation right now.

Three of those 'contributors' are inactive accounts, that are only listed as contributors because they _happened_ to be members of the initial CWDG team. Even if we were to get in touch with them, they **shouldn't** have a say in the matter.

**Comment by keeakita** [comment]
Feel free to remove accounts that did not contribute any code or content to the repository. But if there is even a single byte of contribution from someone, we need their permission. Even if it was intended to be MIT in the first place, the lack of `LICENSE` file or headers means that it never actually was, so this is essentially a license change. I'm not trying to make this needlessly dramatic, but license changes are something you have to make sure you get right because getting this wrong can get our repo taken down. We only need 3 more people to consent by the looks of it, so its not like there's a lot left for us to do besides get in contact and wait.

**Comment by afuhrtrumpet** [comment]
I vote for MIT license. Yay.

**Comment by benlk** [comment]
I'm in favor.

**Comment by bsilvereagle** [comment]
![capture](https://cloud.githubusercontent.com/assets/5597239/13676189/d2307cb4-e6b2-11e5-8a09-c6c5ebef3bd5.PNG)

It looks to me like the three people that were crossed out do indeed have bytes in the code.

**Comment by keeakita** [comment]
@bsilvereagle Thanks, checklist updated to restore them. That puts us 4 people away.

**Comment by paradigm** [comment]
No objection here, licensing to MIT is fine with me.

**Comment by J3RN** [comment]
Alright, I think the last three are CWDGers, and may be hard to reach. I could send out a request on the mailing list for the people to come forward, but I can't promise anything.

**Comment by keeakita** [comment]
Since Eli did essentially a reboot in ad4da552372279b2fc86c0f9405e9988c0d3f0bd we can rebase and remove the code from two of those people. I'd have to first figure out how to do that, and then it looks like one of the files is still tied to a commit by Ryan.

**Comment by egladman** [comment]
On [April 23 2015](https://github.com/OSUOSC/open-source-club-website/commit/ea798362fa80ea5597a72e1e3b232c4c4ce1d50a) I re-wrote the site so @deadant2 and @ryanconnorh0's code is no longer present. Most of their 'contributions' where auto generated code from skel anyways, a dependency that is no longer used. As for @jib5920's contribution, he simply rephrased the club's prior IRC instructions.

**Comment by keeakita** [comment]
The git blame shows that even during that rewrite a part of `_site/README.md` come from Ryan (commit 840ecbbc specifically). Otherwise I would have done the rebase already since it's would have just been removing all previous commits. Weeding this information out is a slight bit more complicated than I hoped, but should be possible since his contribution isn't in the README anymore (and I believe that file has been deleted). I'm going to talk with @J3RN about it since he said he has rebase experience. I'm thinking if I can get to a state where every single line belongs to Eli (as indicated by git blame) we can just wipe history previous to that, then we don't have a problem

**Comment by egladman** [comment]
@oslerw update?

**Comment by Nefari0uss** [comment]
Any updates?

**Comment by egladman** [comment]
It's almost been two weeks since I last inquired. What's the hold up?

**Comment by moore3071** [comment]
In order to get around the contributions made by the members we can't contact, we are going to most likely need to edit history (scary times) to get rid of their contributions so we can license the site. This might not happen until the summer when everyone has more time.

**Comment by egladman** [comment]
@moore3071 and I came up with a potential resolution. Instead of licensing the entire repo we put a clause in the license saying the license begins at ea798362fa80ea5597a72e1e3b232c4c4ce1d50a. This is easier than rebasing commits.

**Comment by moore3071** [comment]
Code newer than ea79836 is now licensed under the MIT license. If @deadant2, @jib5920, @ryanconnorh0 do end up seeing this, please comment and let us know if we can go ahead and get this whole repo licensed. For now though, I'll close this issue.
