### ISSUE TITLE
Proposal: set up a temporary osuosc.github.io page

### ISSUE THREAD

**Issue by benlk** [CWDG/open-source-club-website#275]
### Expected behavior

https://opensource.osu.edu/ loads

### Actual behavior

https://opensource.osu.edu/ does not load

### Proposed solution

1. A person with repo-creation permissions in the @osuosc organization creates a new repo named `osuosc.github.io` and enables GitHub pages on it, and gives @OSUOSC/website-team access to the repo: https://guides.github.com/features/pages/
2. The repo gains an `index.html` with the following content:
    - a short explanation of why https://opensource.osu.edu/ is dead (not assigning blame)
    - the status of the conversation with OSU on resurrecting the stite
    - when the next anticipated update is
    - the date and time of the next meeting, and the subject thereof.

**Comment by benlk** [comment]
Basically: create the repo and giz me access, and I'll build the website for you and hope that you maintain it.

**Comment by smacz42** [comment]
If the expected behavior is that  "https://opensource.osu.edu/ loads", then there will have to be a DNS change in which `opensource.osu.edu` resolves to the github page. This would required that OSU ETS inserts a CNAME into their DNS which points to the correct DNS name for this page.

Additionally, as discussed before, there are several plugins that are not whitelisted on github.io which would prevent the site from automatically being able to be managed by github pages. Therefore it would have to be an assortment of static files being put in a repository that would require manual intervention every time that a change is made.

As we are in a general restructuring period (more than you may be privy to), this is perhaps overkill as we already have information distribution channels, such as the mailing list and the OSC twitter account until such time as service can be restored. It is more a matter of bureaucracy than technology as to why the website is inactive for the moment, and I am of the opinion that we should do it right, than do it quickly; thereby giving our future officers security at the cost of current convenience.

If you have any questions regarding the status of the network connectivity, you may contact any of the officers, as you know many of them personally. And as for external entities, we are willing to accept the temporary risk that we do not currently have a website for a short period of time in exchange for the relatively smooth transition to a sustainable environment for future club officers and members.

**Comment by benlk** [comment]
Paraphrasing from #osuosc:

I'm not asking that we point opensource.osu.edu here. I'm saying that we need a separate webpage, completely outside of OSU's IT infrastructure, that we can point people to when the club website is down.

**Comment by smacz42** [comment]
From #osuosc:

1. The site is not a full copy of the club site, but rather an placeholder in the event that the site is down
2. DNS will _not_ redirect to this site, it will be available separately at `https://osuosc.github.io`
3. The page will check the return code of `https://opensource.osu.edu` to determine if the site is up and will:
  a. redirect to `https://opensource.osu.edu` in the even that the return code is 2xx or 3xx
  b. Display a nicely formatted message to the user that the site is down in the event of any other return code, along with contact information for the club.

Therefore, for those who do not know that this exists, it is worthless, as `https://opensource.osu.edu` will never inform the user of this site. And for those who _do_ know it exists, it is the equivalent of `curl -s -o /dev/null -w "%{http_code}" https://opensource.osu.edu` - or `.isup opensource.osu.edu` in #osuosc - given that the **most likely** scenario is that the users who are aware of the github.io site are also in the chatroom.

If its goal is to inform unaware users of the status of the website, it fails miserably. Those who are truely concerned have shown repeatedly that raising the issue in #osuosc is the easiest and quickest way to get _quality_ information on the situation.

**Comment by benlk** [comment]
> If its goal is to inform unaware users of the status of the website, it fails miserably.

Its expected users know *that* the main website is down. This is a place to host an explanation for *why* the main website is down, *when* the main website is down.

> Those who are truely concerned have shown repeatedly that raising the issue in #osuosc is the easiest and quickest way to get quality information on the situation.

That sample is biased towards people who are already in #osuosc. People who are not already in #osuosc who desire more information must learn about #osuosc from somewhere. Where will they learn about it? The club website links to the Matrix bridge (and IRC), but when the website is down, someone who does not know about #osuosc on Freenode will not be able to learn about the IRC channel without doing serious legwork.

Yes, people will link to the proposed website from #osuosc. But the club can also link to it from club social media and emails, if the website is down. It's useful for situations like, say, the entire first half of the Fall 2017 semester.

The proposed static site's feature list now includes:

- a JavaScript-based status checker for opensource.osu.edu:
    - if up: display a big button linking to main website, but not automatically redirect
    - if fail: display error message:
        - if there is a known outage, officers/people with commit access to the osuosc.github.io repo would write a short explanation
        - if there is no valid explanation message (probably implemented with a time scale for known outages) then a default explanation message is shown.
    - if no JavaScript: explain that the outage checker requires Javascript, and ask them to run their own status checks. Ideally, the noscript option would display that same error message.
- a place to display other messages, such as upcoming events
- Links to ways to contact the club, including IRC, Matrix, and officers email.

This is meant to be an existing fallback/status page, similar to https://status.aws.amazon.com/ or https://status.github.com/messages, which people can be linked to when the primary site is down.

Yes, the likely most-frequent users of this site will be people who care about the club are already in #osuosc. When the site is down for a known reason, people who know that reason should update this site, and link to this website in IRC and other social media, so that the explanation doesn't have to be repeated many times. This is so that #osuosc doesn't get flooded with "the site's down, what's the meeting topic?" or "when is Stallman/idle2 expected to be back up?" and so that people can point to the published statement rather than spending time repeating themselves on the topic.
