### ISSUE TITLE
announce that our server will be down for scheduled maintenance

### ISSUE THREAD

**Issue by egladman** [CWDG/open-source-club-website#91]

**Comment by keeakita** [comment]
The maintenance this issue was originally created for has passed since it we couldn't actually update the site then. But I'm keeping this open for the _next_ maintenance window where I undo gluster and install the new power supply. I'll try and have this done tonight, pending a chat about when we actually want to have that downtime (probably Sunday)

**Comment by egladman** [comment]
@oslerw is 77e640b sufficient?

**Comment by keeakita** [comment]
Looks great, thanks for taking care of this!
